import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "@/app/styles/globals.scss";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  weight: ["400", "600"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={quicksand.className}>
      <body >
        <Navbar />
        <main
          style={{
            flex: 1,
            display: "flex",
            flexDirection: "column",
            padding: "1rem",
          }}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
